### ISSUE TITLE
Strange behavior of the ORG pseudo-op in zas4 assembler

### ISSUE THREAD

**Issue by Alex7634** [ogdenpm/hitech#2]
![org](https://github.com/ogdenpm/hitech/assets/104291705/8d4a692c-7cb1-4b19-8051-db35543e5e47)

note:
in the decompiled version of zas for win x64, the ORG pseudo-op behaves as expected.

**Comment by ogdenpm** [comment]
Updated zas4 code, there was a minor error in parse.c T_OPT case, which used pMaxLoc rather  then pCurLoc

**Comment by Alex7634** [comment]
Checked it out. Everything is fine now.
Thanks!
